const avatars=['🦊','🦉','🐼','🐬','🐯','🐲','🦁','🐸','🐧','🦄','🐺','🐙'];
const tracks={
 discoverer:{name:'Upptäckaren',desc:'Grundläggande språk och cirka år 2-nivå',questions:[
  {type:'Bildord',q:'Vilket ord passar till bilden?',a:['hund','hus','boll'],c:0,word:'hund',help:'En hund är ett djur som kan vara ett sällskapsdjur.',img:'🐕',label:'Ett djur'},
  {type:'Motsatser',q:'Vilket ord betyder tvärtom mot stor?',a:['liten','snäll','rund'],c:0,word:'motsats',help:'En motsats betyder tvärtom. Stor och liten är motsatser.',img:'🐘 / 🐭',label:'Stor och liten'},
  {type:'Bildord',q:'Vad gör personen?',a:['läser','sover','simmar'],c:0,word:'läser',help:'Att läsa är att förstå skrivna ord och meningar.',img:'🧒📖',label:'Läser en bok'},
  {type:'Synonymer',q:'Vilket ord betyder nästan samma sak som glad?',a:['lycklig','arg','trött'],c:0,word:'synonym',help:'Glad och lycklig betyder nästan samma sak.',img:'😊',label:'Glad'},
  {type:'Meningen',q:'Vilket ord passar? Katten ___ på stolen.',a:['sitter','flyger','läser'],c:0,word:'sitter',help:'Sitter betyder att vila med kroppen på en stol eller annan plats.',img:'🐈🪑',label:'Katt på stol'},
  {type:'Skolord',q:'Vad betyder lyssna?',a:['höra noga','springa fort','rita en bild'],c:0,word:'lyssna',help:'Att lyssna är att försöka höra och förstå.',img:'👂',label:'Lyssna'},
  {type:'Bildord',q:'Vilken årstid visar bilden?',a:['vinter','sommar','vår'],c:0,word:'vinter',help:'På vintern kan det vara kallt och snöa.',img:'❄️⛄',label:'Snö och snögubbe'},
  {type:'Motsatser',q:'Vilket ord betyder tvärtom mot varm?',a:['kall','mjuk','ljus'],c:0,word:'kall',help:'Varm och kall är motsatser.',img:'🔥 / 🧊',label:'Varm och kall'},
  {type:'Begrepp',q:'Vad är en rubrik?',a:['Textens namn','Sista ordet','En bild'],c:0,word:'rubrik',help:'Rubriken berättar vad en text kan handla om.',img:'📰',label:'Rubrik över en text'},
  {type:'Meningen',q:'Vilket ord passar? Vi ___ fotboll på rasten.',a:['spelar','äter','skriver'],c:0,word:'spelar',help:'Spelar kan betyda att delta i en lek eller sport.',img:'⚽',label:'Fotboll'}]},
 adventurer:{name:'Äventyraren',desc:'Mellannivå och cirka år 4–5',questions:[
  {type:'Synonymjakt',q:'Vilket ord betyder ungefär samma sak som modig?',a:['tapper','rädd','långsam','tyst'],c:0,word:'tapper',help:'Tapper betyder modig och villig att våga.',img:'🛡️',label:'Vågar trots svårighet'},
  {type:'Motsatsmästaren',q:'Vilket ord är motsatsen till sällsynt?',a:['vanlig','dyrbar','gammal','viktig'],c:0,word:'sällsynt',help:'Sällsynt betyder att något inte förekommer ofta.',img:'⭐',label:'Något ovanligt'},
  {type:'Begreppslabbet',q:'Vad betyder att beskriva?',a:['Berätta hur något är','Säga vad man tycker','Skriva av en text','Ställa en fråga'],c:0,word:'beskriva',help:'Att beskriva är att berätta hur någon eller något är.',img:'🖼️✍️',label:'Berätta med detaljer'},
  {type:'Ord i sammanhang',q:'Mira var ___ när hon kontrollerade varje svar två gånger.',a:['noggrann','förvirrad','hastig','ointresserad'],c:0,word:'noggrann',help:'Noggrann betyder att göra något omsorgsfullt och kontrollera detaljer.',img:'🔍✅',label:'Kontrollerar noga'},
  {type:'Skolord',q:'Vad ska du göra när du ska förklara?',a:['Berätta hur eller varför','Bara skriva ett ord','Rita utan text','Kopiera frågan'],c:0,word:'förklara',help:'Att förklara är att göra något tydligare genom att berätta hur eller varför.',img:'💬💡',label:'Göra något tydligt'},
  {type:'Synonymjakt',q:'Vilket ord är en synonym till avsluta?',a:['slutföra','påbörja','undersöka','förändra'],c:0,word:'slutföra',help:'Slutföra betyder att göra klart.',img:'🏁',label:'Göra klart'},
  {type:'Begreppslabbet',q:'Vad är en sammanfattning?',a:['Det viktigaste i kort form','En lång ny berättelse','En lista med alla ord','En personlig åsikt'],c:0,word:'sammanfattning',help:'En sammanfattning återger textens viktigaste innehåll med färre ord.',img:'📄➡️📝',label:'Kortare version'},
  {type:'Ord i sammanhang',q:'Vilket ord passar? Klassen skulle ___ två olika djur.',a:['jämföra','avsluta','gömma','förneka'],c:0,word:'jämföra',help:'Att jämföra är att undersöka likheter och skillnader.',img:'🐺↔️🦊',label:'Likheter och skillnader'},
  {type:'Skolord',q:'Vad betyder att resonera?',a:['Utveckla tankar med skäl och exempel','Svara ja eller nej','Läsa snabbt','Skriva av en mening'],c:0,word:'resonera',help:'Att resonera är att utveckla tankar och koppla dem till skäl och exempel.',img:'🧠💬',label:'Tänka och förklara'},
  {type:'Motsatsmästaren',q:'Vilket ord är motsatsen till tydlig?',a:['otydlig','enkel','viktig','noggrann'],c:0,word:'tydlig',help:'Tydlig betyder lätt att förstå. Otydlig betyder svår att förstå.',img:'🌫️',label:'Svårt att se eller förstå'}]},
 master:{name:'Mästaren',desc:'Utmanande språk på år 6-nivå',questions:[
  {type:'Akademiskt språk',q:'Vilket ord är den bästa synonymen till väsentlig?',a:['avgörande','tillfällig','obetydlig','vanlig'],c:0,word:'väsentlig',help:'Väsentlig betyder mycket viktig eller central.',img:'🎯',label:'Det mest centrala'},
  {type:'Begreppslabbet',q:'Vad innebär det att analysera en text?',a:['Undersöka delar, samband och betydelser','Återge texten ord för ord','Bara säga om texten är bra','Läsa texten så snabbt som möjligt'],c:0,word:'analysera',help:'Att analysera är att undersöka delar och samband för att förstå helheten bättre.',img:'🔎📄',label:'Undersöka textens delar'},
  {type:'Ord i sammanhang',q:'Vilket ord passar bäst? Författarens budskap var ___ och kunde förstås på flera sätt.',a:['mångtydigt','självklart','oviktigt','bokstavligt'],c:0,word:'mångtydig',help:'Mångtydig betyder att något kan tolkas på flera olika sätt.',img:'🛤️🛤️',label:'Flera möjliga tolkningar'},
  {type:'Skolord',q:'Vilket svar visar bäst vad det innebär att underbygga ett resonemang?',a:['Stödja tankar med skäl, exempel eller fakta','Skriva fler meningar utan samband','Upprepa samma åsikt flera gånger','Använda så svåra ord som möjligt'],c:0,word:'underbygga',help:'Att underbygga är att stärka ett påstående med relevanta skäl, exempel eller fakta.',img:'🏗️💬',label:'Bygga stöd för en tanke'},
  {type:'Synonymjakt',q:'Vilket ord ligger närmast betydelsen av konsekvens?',a:['följd','orsak','åsikt','möjlighet'],c:0,word:'konsekvens',help:'En konsekvens är det som händer som följd av något annat.',img:'🁢➡️🁢',label:'Något leder till något annat'},
  {type:'Begreppslabbet',q:'Vad är en slutsats i en resonerande text?',a:['En tanke som bygger på textens skäl och exempel','Textens första mening','Ett nytt ämne utan koppling','En fråga som aldrig besvaras'],c:0,word:'slutsats',help:'En slutsats är det resultat man kommer fram till efter att ha vägt samman information och resonemang.',img:'🧩✅',label:'Delarna leder till ett resultat'},
  {type:'Ord i sammanhang',q:'Vilket ord passar bäst? Källans uppgifter behöver ___ innan de används.',a:['granskas','antas','förkortas','ignoreras'],c:0,word:'granska',help:'Att granska är att undersöka något noggrant och kritiskt.',img:'🕵️📄',label:'Kontrollera en källa'},
  {type:'Akademiskt språk',q:'Vilket ord betyder att två uppgifter inte stämmer överens?',a:['motsäger','bekräftar','sammanfattar','förtydligar'],c:0,word:'motsäga',help:'Att motsäga betyder att säga eller visa något som inte stämmer med ett annat påstående.',img:'↔️❌',label:'Uppgifter krockar'},
  {type:'Skolord',q:'Vilken formulering visar ett nyanserat resonemang?',a:['Det finns både fördelar och nackdelar beroende på situationen.','Det är alltid bäst, punkt slut.','Alla tycker exakt likadant.','Det finns bara ett möjligt svar.'],c:0,word:'nyanserad',help:'Ett nyanserat resonemang visar flera perspektiv, undantag eller grader.',img:'⚖️',label:'Flera perspektiv'},
  {type:'Begreppslabbet',q:'Vad betyder implicit information?',a:['Information som antyds men inte sägs direkt','Information som står i rubriken','Information som upprepas flera gånger','Information som saknar betydelse'],c:0,word:'implicit',help:'Implicit information är underförstådd och behöver tolkas med hjälp av ledtrådar.',img:'🧊',label:'Mer finns under ytan'}]}}
const wordInfo={};Object.values(tracks).forEach(t=>t.questions.forEach(q=>wordInfo[q.word]=[q.help,q.label]));
const defaults={name:'Elev',avatar:'🦊',xp:0,best:0,words:[],autoSpeak:false,easySupport:false,imageSupport:true,track:'discoverer',played:0};
let state={...defaults,...JSON.parse(localStorage.getItem('svenskamastarna41')||localStorage.getItem('svenskamastarna4')||'{}')};let selectedAvatar=state.avatar,selectedTrack=state.track||'discoverer',questions=[],index=0,score=0,earned=0,answered=false;
const $=id=>document.getElementById(id);const save=()=>{localStorage.setItem('svenskamastarna41',JSON.stringify(state));renderHud()};const level=()=>Math.floor(state.xp/150)+1;
function speak(text){if(!('speechSynthesis'in window))return;speechSynthesis.cancel();const u=new SpeechSynthesisUtterance(text);u.lang='sv-SE';u.rate=.9;speechSynthesis.speak(u)}
function showView(id){document.querySelectorAll('.view').forEach(v=>v.classList.toggle('active',v.id===id));document.querySelectorAll('.nav-tabs button').forEach(b=>b.classList.toggle('active',b.dataset.view===id));scrollTo({top:0,behavior:'smooth'});if(id==='badges')renderBadges();if(id==='words')renderWords();if(id==='profile')renderProfile()}
document.addEventListener('click',e=>{const b=e.target.closest('[data-view]');if(b)showView(b.dataset.view)});
function renderHud(){const l=level(),progress=(state.xp%150)/150*100;$('miniAvatar').textContent=state.avatar;$('miniName').textContent=state.name;$('level').textContent=l;$('xp').textContent=state.xp;$('xpBar').style.width=progress+'%';$('heroAvatar').textContent=state.avatar;$('heroLevel').textContent=l;$('homeXp').textContent=state.xp;$('badgeCount').textContent=getBadges().filter(b=>b.ok).length;$('wordCount').textContent=state.words.length;$('worldStars').textContent=state.best>=9?'★ ★ ★':state.best>=7?'★ ★ ☆':state.best>=5?'★ ☆ ☆':'☆ ☆ ☆';$('activeTrackPill').textContent=tracks[state.track].name}
function renderProfile(){$('profileAvatar').textContent=selectedAvatar;$('profileName').textContent=state.name;$('profileLevel').textContent=level();$('profileXpBar').style.width=((state.xp%150)/150*100)+'%';$('nameInput').value=state.name;$('autoSpeak').checked=state.autoSpeak;$('easySupport').checked=state.easySupport;$('imageSupport').checked=state.imageSupport;$('avatarPicker').innerHTML='';avatars.forEach(a=>{const b=document.createElement('button');b.className='avatar-option'+(a===selectedAvatar?' selected':'');b.textContent=a;b.onclick=()=>{selectedAvatar=a;renderProfile()};$('avatarPicker').appendChild(b)});document.querySelectorAll('#trackPicker button').forEach(b=>b.classList.toggle('selected',b.dataset.track===selectedTrack))}
document.querySelectorAll('#trackPicker button').forEach(b=>b.onclick=()=>{selectedTrack=b.dataset.track;renderProfile()});
$('saveProfile').onclick=()=>{state.name=$('nameInput').value.trim()||'Elev';state.avatar=selectedAvatar;state.track=selectedTrack;state.imageSupport=$('imageSupport').checked;state.autoSpeak=$('autoSpeak').checked;state.easySupport=$('easySupport').checked;save();renderProfile();$('saveMessage').textContent='Profil och nivåspår är sparade!';setTimeout(()=>$('saveMessage').textContent='',1800)};
$('openAcademy').onclick=startGame;$('playAgain').onclick=startGame;function startGame(){questions=tracks[state.track].questions;index=0;score=0;earned=0;answered=false;showView('academy');renderQuestion()}
function renderQuestion(){answered=false;const q=questions[index];$('questionNumber').textContent=`${index+1}/${questions.length}`;$('questionProgress').style.width=((index+1)/questions.length*100)+'%';$('taskType').textContent=`${tracks[state.track].name} • ${q.type}`;$('questionText').textContent=q.q;$('questionImage').innerHTML=`<span class="picture">${q.img}</span><span class="picture-label">${q.label}</span>`;$('questionImage').classList.toggle('hidden',!state.imageSupport);$('supportBox').innerHTML=`<strong>${q.word}</strong><br>${q.help}`;$('supportBox').classList.toggle('hidden',!state.easySupport);$('feedback').className='feedback hidden';$('nextQuestion').classList.add('hidden');$('answers').innerHTML='';q.a.forEach((text,i)=>{const b=document.createElement('button');b.className='answer';b.textContent=text;b.onclick=()=>answer(i,b);$('answers').appendChild(b)});if(state.autoSpeak)setTimeout(()=>speak(q.q),250)}
function answer(choice,button){if(answered)return;answered=true;const q=questions[index];document.querySelectorAll('.answer').forEach((b,i)=>{b.disabled=true;if(i===q.c)b.classList.add('correct')});if(choice===q.c){score++;earned+=15;button.classList.add('correct');$('feedback').textContent='Rätt! Du fick 15 XP.';$('feedback').className='feedback good'}else{button.classList.add('wrong');$('feedback').textContent=`Inte riktigt. Rätt svar är: ${q.a[q.c]}.`;$('feedback').className='feedback bad'}if(!state.words.includes(q.word))state.words.push(q.word);$('nextQuestion').classList.remove('hidden')}
$('nextQuestion').onclick=()=>{index++;index<questions.length?renderQuestion():finishGame()};$('speakQuestion').onclick=()=>{const q=questions[index];speak(q.q+' '+q.a.join('. '))};$('toggleSupport').onclick=()=>$('supportBox').classList.toggle('hidden');
function finishGame(){const bonus=score>=9?90:score>=7?60:score>=5?35:20;earned+=bonus;state.xp+=earned;state.best=Math.max(state.best,score);state.played++;save();$('resultMedal').textContent=score>=9?'🥇':score>=7?'🥈':'🥉';$('scoreValue').textContent=`${score}/${questions.length}`;$('earnedXp').textContent=earned;$('resultText').textContent=`Du klarade ${tracks[state.track].name} med ${score} rätt. `+(score>=9?'Fantastiskt resultat!':score>=7?'Bra jobbat!':'Träna gärna en gång till.');showView('result')}
function getBadges(){return[{icon:'🌟',name:'Första steget',text:'Spela ett uppdrag.',ok:state.played>=1},{icon:'⚡',name:'XP-jägaren',text:'Samla 100 XP.',ok:state.xp>=100},{icon:'📚',name:'Ordsamlaren',text:'Samla 5 begrepp.',ok:state.words.length>=5},{icon:'🥇',name:'Guldmästaren',text:'Få minst 9 rätt.',ok:state.best>=9},{icon:'🎯',name:'Träffsäker',text:'Få minst 7 rätt.',ok:state.best>=7},{icon:'👑',name:'Språkhjälten',text:'Nå nivå 3.',ok:level()>=3}]}
function renderBadges(){$('badgeGrid').innerHTML='';getBadges().forEach(b=>$('badgeGrid').insertAdjacentHTML('beforeend',`<article class="badge-card ${b.ok?'':'locked-badge'}"><div class="badge-icon">${b.ok?b.icon:'🔒'}</div><div><h3>${b.name}</h3><p>${b.text}</p></div></article>`))}
function renderWords(){$('wordGrid').innerHTML='';if(!state.words.length){$('wordGrid').innerHTML='<article class="word-card"><h3>Inga ord ännu</h3><p>Spela Ordakademin så samlas nya ord här automatiskt.</p></article>';return}state.words.forEach(w=>{const info=wordInfo[w]||['Ett nytt ord från spelet.','Spela vidare för fler exempel.'];$('wordGrid').insertAdjacentHTML('beforeend',`<article class="word-card"><h3>${w}</h3><p>${info[0]}</p><p><em>${info[1]}</em></p><button onclick="speak('${w}. ${info[0]}')">🔊 Lyssna</button></article>`)})}
renderHud();renderProfile();renderBadges();renderWords();


// Version 5.1: skriv orden själv med tangentbordet
const spellingAreas={
 sj:{name:'Sj-ljudet',icon:'🌊',desc:'sj, skj, stj, sk, ch och sch',words:[['stjärna','stjär-na','En lysande himlakropp.','⭐',['sjärna','skärna']],['skjorta','skjor-ta','Ett klädesplagg.','👕',['sjorta','stjorta']],['sjuksköterska','sjuk-skö-ters-ka','En person som arbetar med vård.','🏥',['sjuk sköterska','skuksköterska']],['journalist','jour-na-list','En person som arbetar med nyheter.','📰',['jornalist','journaist']],['choklad','cho-klad','Något som görs av kakao.','🍫',['sjoklad','shoklad']],['schema','sche-ma','En plan över tider och aktiviteter.','📅',['sjema','skema']]]},
 tj:{name:'Tj-ljudet',icon:'🔔',desc:'tj, k och kj',words:[['tjugo','tju-go','Talet 20.','2️⃣0️⃣',['kjugo','chugo']],['kyrka','kyr-ka','En byggnad för gudstjänster.','⛪',['tjyrka','kyrcka']],['källa','käl-la','Där information eller vatten kommer ifrån.','💧',['tjälla','kjälla']],['kök','kök','Ett rum där man lagar mat.','🍳',['tjök','kjök']],['tjänst','tjänst','Ett arbete eller något som erbjuds.','💼',['känst','chänst']],['kedja','ked-ja','Länkar som sitter ihop.','⛓️',['tjedja','kjedja']]]},
 j:{name:'J-ljudet',icon:'🎵',desc:'j, gj, hj, dj och lj',words:[['hjärna','hjär-na','Organet vi tänker med.','🧠',['järna','gjärna']],['hjärta','hjär-ta','Organet som pumpar blod.','❤️',['järta','gjärta']],['djur','djur','En levande varelse.','🐾',['jur','gjur']],['ljud','ljud','Något som vi kan höra.','🔊',['jud','djud']],['gjorde','gjor-de','Dåtid av göra.','🛠️',['jorde','djorde']],['hjul','hjul','En rund del som kan rulla.','🛞',['jul','gjul']]]},
 double:{name:'Dubbelteckning',icon:'✌️',desc:'Kort vokal och dubbel konsonant',words:[['katt','katt','Ett vanligt husdjur.','🐈',['kat','kaat']],['glass','glass','En kall efterrätt.','🍦',['glas','glaas']],['hoppa','hop-pa','Att lämna marken med båda fötterna.','🦘',['hopa','hopppa']],['sommar','som-mar','Årstiden efter våren.','☀️',['somar','sommmar']],['snabb','snabb','Något som rör sig fort.','⚡',['snab','snaabb']],['vissla','viss-la','Att skapa en ton med munnen.','🎶',['visla','visssla']]]},
 compounds:{name:'Särskrivning',icon:'🧩',desc:'Sammansatta ord skrivs ihop',words:[['sjuksköterska','sjuk-skö-ters-ka','En person som arbetar med vård.','🏥',['sjuk sköterska','sjuks köterska']],['jättebra','jät-te-bra','Något som är mycket bra.','🌟',['jätte bra','jät tebra']],['fotbollsplan','fot-bolls-plan','En plan där man spelar fotboll.','⚽',['fotbolls plan','fot bollsplan']],['glasskiosk','glass-ki-osk','En kiosk som säljer glass.','🍦',['glass kiosk','glas skiosk']],['klassrumsdörr','klass-rums-dörr','Dörren till ett klassrum.','🚪',['klassrums dörr','klass rumsdörr']],['sommarlov','som-mar-lov','Skolledighet på sommaren.','🏖️',['sommar lov','som marl ov']]]}
};
state.spelling=state.spelling||{};state.spellingBest=state.spellingBest||{};
let spArea='sj',spQs=[],spI=0,spScore=0,spXp=0,spAnswered=false,spPersonal=false;
function spEntry(q){return state.spelling[q.word]||(state.spelling[q.word]={wrong:0,correct:0,streak:0,mastered:false,syllables:q.syllables,help:q.help})}
function makeQuestions(key){return spellingAreas[key].words.map((w,i)=>{let [word,syllables,help,img,wrong]=w;let typing=i%2===1;let options=[word,...wrong].sort(()=>Math.random()-.5);return{word,syllables,help,img,typing,options}})}
function renderAreas(){let g=$('spellingAreaGrid');if(!g)return;g.innerHTML='';Object.entries(spellingAreas).forEach(([k,a])=>{let b=document.createElement('button');b.className='area-card';b.innerHTML=`<span class="area-icon">${a.icon}</span><h3>${a.name}</h3><p>${a.desc}</p>`;b.onclick=()=>startArea(k);g.appendChild(b)})}
function startArea(k){spArea=k;spPersonal=false;spQs=makeQuestions(k);startSpelling()}
function startSpelling(){spI=0;spScore=0;spXp=0;showView('spellinggame');renderSpQ()}
function renderSpQ(){spAnswered=false;let q=spQs[spI];$('spellingNumber').textContent=`${spI+1}/${spQs.length}`;$('spellingProgress').style.width=((spI+1)/spQs.length*100)+'%';$('spellingType').textContent=q.typing?'⌨️ Skriv själv':'✓ Välj rätt';$('spellingQuestion').textContent=q.typing?'Skriv ordet som passar till bilden och förklaringen.':'Vilket ord är rätt stavat?';$('spellingImage').innerHTML=`<span class="picture">${q.img}</span><span class="picture-label">${q.help}</span>`;$('syllableBox').innerHTML=`<strong>Stavelser:</strong> <span class="syllables">${q.syllables}</span>`;$('syllableBox').classList.add('hidden');$('spellingFeedback').className='feedback hidden';$('nextSpelling').classList.add('hidden');$('spellingAnswers').innerHTML='';$('typingForm').classList.toggle('hidden',!q.typing);if(q.typing){$('typingInput').value='';setTimeout(()=>$('typingInput').focus(),100)}else q.options.forEach(t=>{let b=document.createElement('button');b.className='answer';b.textContent=t;b.onclick=()=>markSpelling(t===q.word,b);$('spellingAnswers').appendChild(b)});if(state.autoSpeak)setTimeout(()=>speak(q.help+' '+(q.typing?'Skriv ordet.':q.options.join('. '))),250)}
function normalize(s){return s.trim().toLocaleLowerCase('sv-SE').replace(/\s+/g,' ')}
function markSpelling(ok,button){if(spAnswered)return;spAnswered=true;let q=spQs[spI],e=spEntry(q);if(ok){spScore++;spXp+=q.typing?20:15;e.correct++;e.streak++;if(e.streak>=3)e.mastered=true;$('spellingFeedback').textContent=`Rätt! ${q.typing?'Du skrev ordet själv och fick 20 XP.':'Du fick 15 XP.'}`;$('spellingFeedback').className='feedback good';if(button)button.classList.add('correct')}else{e.wrong++;e.streak=0;e.mastered=false;$('spellingFeedback').textContent=`Inte riktigt. Rätt stavning är: ${q.word}. Ordet har sparats i stavningsboken.`;$('spellingFeedback').className='feedback bad';if(button)button.classList.add('wrong')}save();document.querySelectorAll('#spellingAnswers .answer').forEach(b=>{b.disabled=true;if(b.textContent===q.word)b.classList.add('correct')});$('typingInput').disabled=q.typing;$('nextSpelling').classList.remove('hidden')}
$('typingForm').onsubmit=e=>{e.preventDefault();let q=spQs[spI];markSpelling(normalize($('typingInput').value)===normalize(q.word))};
$('nextSpelling').onclick=()=>{spI++;if(spI<spQs.length)renderSpQ();else finishSp()};
function finishSp(){let bonus=spScore===spQs.length?50:spScore>=4?30:15;spXp+=bonus;state.xp+=spXp;if(!spPersonal)state.spellingBest[spArea]=Math.max(state.spellingBest[spArea]||0,spScore);save();$('spellingMedal').textContent=spScore===spQs.length?'🥇':spScore>=4?'🥈':'🥉';$('spellingResultTitle').textContent='Stavningsträningen är klar!';$('spellingResultText').textContent='Du har både valt rätt stavning och skrivit ord med tangentbordet.';$('spellingScore').textContent=`${spScore}/${spQs.length}`;$('spellingXp').textContent=spXp;showView('spellingresult')}
function renderBook(){let es=Object.entries(state.spelling),g=$('spellingBookGrid');$('needsCount').textContent=es.filter(([,e])=>!e.mastered).length;$('masteredCount').textContent=es.filter(([,e])=>e.mastered).length;$('bookEmpty').classList.toggle('hidden',es.length>0);g.innerHTML='';es.sort((a,b)=>Number(a[1].mastered)-Number(b[1].mastered)||b[1].wrong-a[1].wrong).forEach(([w,e])=>g.insertAdjacentHTML('beforeend',`<article class="word-card"><span class="word-status ${e.mastered?'mastered':''}">${e.mastered?'Bemästrat':'Behöver tränas'}</span><h3>${w}</h3><p class="syllables">${e.syllables}</p><p>${e.help}</p><div class="word-stats"><span>✓ ${e.correct}</span><span>✗ ${e.wrong}</span><span>Serie ${e.streak}/3</span></div><button onclick="speak('${w}. ${e.help}')">🔊 Lyssna</button></article>`))}
function trainWords(){let pool=Object.values(spellingAreas).flatMap(a=>a.words).map(w=>({word:w[0],syllables:w[1],help:w[2],img:w[3],typing:true,options:[w[0],...w[4]]}));spQs=Object.entries(state.spelling).filter(([,e])=>!e.mastered).map(([w])=>pool.find(q=>q.word===w)).filter(Boolean).slice(0,10);if(!spQs.length){alert('Spela först ett område så att svåra ord kan samlas in.');return}spPersonal=true;startSpelling()}
const oldShow=showView;showView=function(id){oldShow(id);if(id==='spellinghub')renderAreas();if(id==='spellingbook')renderBook()};
$('openSpelling').onclick=()=>showView('spellinghub');$('speakSpelling').onclick=()=>{let q=spQs[spI];speak(q.help+' '+(q.typing?'Skriv ordet.':q.options.join('. ')))};$('syllableHelp').onclick=()=>$('syllableBox').classList.toggle('hidden');$('trainMyWords').onclick=trainWords;$('replaySpelling').onclick=()=>spPersonal?trainWords():startArea(spArea);
renderAreas();renderBook();
